# Generated by Django 3.2 on 2021-04-25 11:07

import TestCreator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('JEE Mains', 'JEE Mains'), ('JEE Advanced', 'JEE Advanced'), ('KVPY', 'KVPY'), ('Bitsat', 'Bitsat')], max_length=100)),
                ('year', models.IntegerField(default=2020, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleIntegerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to=TestCreator.models.create_path)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('QuestionNumber', models.IntegerField(blank=True, null=True)),
                ('QuestionPaper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TestCreator.questionpaper')),
            ],
        ),
    ]
