# Generated by Django 3.2 on 2021-04-28 17:14

import TestCreator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestCreator', '0002_alter_singleintegertype_questionnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='total_number_of_questions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='singleintegertype',
            name='questionType',
            field=models.CharField(default='SingleIntegerType', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.ImageField(upload_to=TestCreator.models.create_path_user)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionPaper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TestCreator.questionpaper')),
            ],
        ),
    ]
