# Generated by Django 3.2 on 2021-04-28 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestCreator', '0003_auto_20210428_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionPaper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TestCreator.questionpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
        migrations.AddField(
            model_name='questionattempts',
            name='Attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TestCreator.attempt'),
        ),
    ]
